[tars]
tars_url = "http://127.0.0.1:3000"
tars_token = ""
tars_pkg_dir = "binary/"

[[machine]]
domain = "tars-node-0.tars-node"
ip = "10.0.0.73"
[[machine]]
domain = "tars-node-1.tars-node"
ip = "10.0.1.193"
[[machine]]
domain = "tars-node-2.tars-node"
ip = "10.0.0.142"

[chain]
chain_id="chain0"
# the rpc-service enable sm-ssl or not, default disable sm-ssl
rpc_sm_ssl=false
# the gateway-service enable sm-ssl or not, default disable sm-ssm
gateway_sm_ssl=false
# the existed rpc service ca path, will generate new ca if not configured
#rpc_ca_cert_path=""
# the existed gateway service ca path, will generate new ca if not configured
#gateway_ca_cert_path="

[[group]]
group_id="group0"
# the genesis configuration path of the group, will generate new genesis configuration if not configured
# genesis_config_path = ""
# VM type, now only support evm/wasm
vm_type="evm"
# use sm-crypto or not
sm_crypto=false
# enable auth-check or not
auth_check=false
init_auth_address=""

# the genesis config
# the number of blocks generated by each leader
leader_period = 1
# the max number of transactions of a block
block_tx_count_limit = 1000
# consensus algorithm now support PBFT(consensus_type=pbft)
consensus_type = "pbft"
# transaction gas limit
gas_limit = "3000000000"
# compatible version, can be dynamically upgraded through setSystemConfig
# the default is 3.0.0-rc4
compatibility_version="3.0.0"

[[agency]]
name = "agencyA"
# enable data disk encryption for rpc/gateway or not, default is false
enable_storage_security = false
# url of the key center, in format of ip:port, please refer to https://github.com/FISCO-BCOS/key-manager for details
# key_center_url = 
# cipher_data_key = 

    [agency.rpc]
    deploy_ip=["tars-node-0.tars-node"]
    listen_ip="0.0.0.0"
    listen_port=20200
    thread_count=4

    [agency.gateway]
    deploy_ip=["tars-node-0.tars-node"]
    listen_ip="0.0.0.0"
    listen_port=30300
    peers=["tars-node-0.tars-node:30300","tars-node-1.tars-node:30300","tars-node-2.tars-node:30300"]

    [[agency.group]]
        group_id = "group0"
        [[agency.group.node]]
        node_name = "node0"
        deploy_ip = "tars-node-0.tars-node"
        # enable data disk encryption for bcos node or not, default is false
        enable_storage_security = false
        # url of the key center, in format of ip:port, please refer to https://github.com/FISCO-BCOS/key-manager for details
        # key_center_url = 
        # cipher_data_key =
        monitor_listen_port = "3902"
        # monitor log path example:"/home/fisco/tars/framework/app_log/" 
        monitor_log_path = "/home/fisco/tars/framework/app_log/" 

[[agency]]
name = "agencyB"
# enable data disk encryption for rpc/gateway or not, default is false
enable_storage_security = false
# url of the key center, in format of ip:port, please refer to https://github.com/FISCO-BCOS/key-manager for details
# key_center_url = 
# cipher_data_key = 

    [agency.rpc]
    deploy_ip=["tars-node-1.tars-node","tars-node-2.tars-node"]
    listen_ip="0.0.0.0"
    listen_port=20200
    thread_count=4

    [agency.gateway]
    deploy_ip=["tars-node-1.tars-node","tars-node-2.tars-node"]
    listen_ip="0.0.0.0"
    listen_port=30300
    peers=["tars-node-0.tars-node:30300","tars-node-1.tars-node:30300","tars-node-2.tars-node:30300"]

    [[agency.group]]
        group_id = "group0"
        [[agency.group.node]]
        node_name = "node1"
        deploy_ip = "tars-node-1.tars-node"
        # enable data disk encryption for bcos node or not, default is false
        enable_storage_security = false
        # url of the key center, in format of ip:port, please refer to https://github.com/FISCO-BCOS/key-manager for details
        # key_center_url = 
        # cipher_data_key =
        monitor_listen_port = "3901"
        # monitor log path example:"/home/fisco/tars/framework/app_log/" 
        monitor_log_path = "/home/fisco/tars/framework/app_log/" 

        [[agency.group.node]]
        node_name = "node2"
        deploy_ip = "tars-node-2.tars-node"
        # enable data disk encryption for bcos node or not, default is false
        enable_storage_security = false
        # url of the key center, in format of ip:port, please refer to https://github.com/FISCO-BCOS/key-manager for details
        # key_center_url = 
        # cipher_data_key =
        monitor_listen_port = "3901"
        # monitor log path example:"/home/fisco/tars/framework/app_log/" 
        monitor_log_path = "/home/fisco/tars/framework/app_log/" 
